reload("options")
reload("keymaps")
reload("plugins")
reload("autocommands")

reload("settings.lvim")

reload("user.alpha")
reload("user.colorsheme")
reload("user.treesitter")
reload("user.null-ls")
reload("user.nvimtree")
reload("user.todo-comments")
reload("user.nvim-colorizer")
reload("user.lsp")
reload("user.zen-mode")
reload("user.fidget")
reload("user.modicator")
-- reload("user.dbee")
