reload("keymaps")
reload("options")
reload("plugins")

reload("settings.lvim")

reload("user.alpha")
reload("user.cmp")
reload("user.colorsheme")
-- reload("user.dbee")
reload("user.dial")
-- reload("user.fidget")
reload("user.lsp")
reload("user.modicator")
reload("user.null-ls")
reload("user.nvim-colorizer")
reload("user.nvimtree")
reload("user.terminal")
reload("user.todo-comments")
reload("user.treesitter")
reload("user.zen-mode")
